$path = 'fe/src/pages/AdminDashboardPage.tsx'
$text = Get-Content -Raw $path

$replacements = @(
  @('Không th? hoàn t?t yêu c?u. Vui lòng th? l?i.','Khong the hoan tat yeu cau. Vui long thu lai.'),
  @('Qu?n tr?','Quan tri'),
  @('Nhân viên','Nhan vien'),
  @('Ngu?i dùng','Nguoi dung'),
  @('Tr?ng thái don hàng không du?c d? tr?ng.','Trang thai don hang khong duoc de trong.'),
  @('Ðã c?p nh?t don #','Da cap nhat don #'),
  @('tr?ng thái','trang thai'),
  @('Ðã c?p nh?t vai trò tài kho?n ','Da cap nhat vai tro tai khoan '),
  @('Ðã khóa tài kho?n ','Da khoa tai khoan '),
  @('Ðã m? khóa tài kho?n ','Da mo khoa tai khoan '),
  @('Tên dang nh?p và m?t kh?u không du?c d? tr?ng.','Ten dang nhap va mat khau khong duoc de trong.'),
  @('Ðã t?o tài kho?n ','Da tao tai khoan '),
  @('v?i vai trò','voi vai tro'),
  @('Ðã xóa tài kho?n ','Da xoa tai khoan '),
  @('Tìm theo tên danh m?c / mã...','Tim theo ten danh muc / ma...'),
  @('Ch?n m?c bên trái d? m? thông tin chi ti?t...','Chon muc ben trai de mo thong tin chi tiet...'),
  @('ÐI?U HU?NG','DIEU HUONG'),
  @('T?ng quan','Tong quan'),
  @('Danh m?c','Danh muc'),
  @('Ðon hàng','Don hang'),
  @('M? trang s?n ph?m','Mo trang san pham'),
  @('B?ng di?u khi?n Admin','Bang dieu khien Admin'),
  @('B?ng di?u khi?n Staff','Bang dieu khien Staff'),
  @('B?NG ÐI?U HÀNH ADMIN','BANG DIEU HANH ADMIN'),
  @('Thông tin danh m?c s?n ph?m','Thong tin danh muc san pham'),
  @('Trung tâm qu?n lý don hàng','Trung tam quan ly don hang'),
  @('Trung tâm qu?n lý ngu?i dùng','Trung tam quan ly nguoi dung'),
  @('Trung tâm di?u hành qu?n tr?','Trung tam dieu hanh quan tri'),
  @('Giao di?n gi?ng Owner d? d? v?n hành, nhung quy?n thao tác theo vai trò Admin/Owner.','Giao dien giong Owner de de van hanh, nhung quyen thao tac theo vai tro Admin/Owner.'),
  @('Admin du?c xem và c?p nh?t tr?ng thái don hàng d? x? lý v?n hành h?ng ngày.','Admin duoc xem va cap nhat trang thai don hang de xu ly van hanh hang ngay.'),
  @('Khu qu?n lý tài kho?n ch? Owner m?i có toàn quy?n t?o/xóa/d?i role/khóa-m?.','Khu quan ly tai khoan chi Owner moi co toan quyen tao/xoa/doi role/khoa-mo.'),
  @('Theo dõi KPI h? th?ng, t?n kho và d? li?u v?n hành trong cùng b? c?c v?i Owner.','Theo doi KPI he thong, ton kho va du lieu van hanh trong cung bo cuc voi Owner.'),
  @('Qu?n lý s?n ph?m','Quan ly san pham'),
  @('Sang b?ng di?u khi?n Staff','Sang bang dieu khien Staff'),
  @('T?ng m?t hàng','Tong mat hang'),
  @('T?ng don hàng','Tong don hang'),
  @('Ðon c?n x? lý','Don can xu ly'),
  @('Nhi?m v? Admin h?ng ngày','Nhiem vu Admin hang ngay'),
  @('CRUD s?n ph?m, danh m?c, thuong hi?u.','CRUD san pham, danh muc, thuong hieu.'),
  @('Xem và c?p nh?t tr?ng thái don hàng.','Xem va cap nhat trang thai don hang.'),
  @('Ki?m tra t?n kho th?p và các l?i d? li?u v?n hành.','Kiem tra ton kho thap va cac loi du lieu van hanh.'),
  @('Owner cao hon Admin và có toàn quy?n qu?n lý tài kho?n h? th?ng.','Owner cao hon Admin va co toan quyen quan ly tai khoan he thong.'),
  @('T?n kho và ch?t lu?ng d? li?u','Ton kho va chat luong du lieu'),
  @('C?nh báo t?n kho th?p','Canh bao ton kho thap'),
  @('Không có s?n ph?m t?n kho th?p.','Khong co san pham ton kho thap.'),
  @('L?i d? li?u c?n x? lý','Loi du lieu can xu ly'),
  @('D? li?u hi?n t?i ?n d?nh.','Du lieu hien tai on dinh.'),
  @('Danh m?c dang l?c','Danh muc dang loc'),
  @('Danh m?c dang ch?n','Danh muc dang chon'),
  @('T?t c?','Tat ca'),
  @('Danh m?c hi?n có','Danh muc hien co'),
  @('Mã danh m?c','Ma danh muc'),
  @('Tên danh m?c','Ten danh muc'),
  @('Hành d?ng','Hanh dong'),
  @('Xem s?n ph?m','Xem san pham'),
  @('Qu?n lý','Quan ly'),
  @('Không có danh m?c phù h?p v?i t? khóa hi?n t?i.','Khong co danh muc phu hop voi tu khoa hien tai.'),
  @('Chi ti?t danh m?c','Chi tiet danh muc'),
  @('M? trang s?n ph?m theo danh m?c','Mo trang san pham theo danh muc'),
  @('M? toàn b? s?n ph?m','Mo toan bo san pham'),
  @('Ch?n m?t danh m?c ? b?ng bên trên d? xem thông tin chi ti?t.','Chon mot danh muc o bang ben tren de xem thong tin chi tiet.'),
  @('Qu?n lý don hàng','Quan ly don hang'),
  @('C?n x? lý','Can xu ly'),
  @('Chua có don hàng d? hi?n th?.','Chua co don hang de hien thi.'),
  @('Mã don','Ma don'),
  @('Khách hàng','Khach hang'),
  @('Ngu?i nh?n','Nguoi nhan'),
  @('T?ng ti?n','Tong tien'),
  @('S? m?t hàng','So mat hang'),
  @('Tr?ng thái hi?n t?i','Trang thai hien tai'),
  @('Thanh toán','Thanh toan'),
  @('C?p nh?t tr?ng thái','Cap nhat trang thai'),
  @('Không rõ','Khong ro'),
  @('Ðang c?p nh?t...','Dang cap nhat...'),
  @('C?p nh?t','Cap nhat'),
  @('Qu?n lý ngu?i dùng','Quan ly nguoi dung'),
  @('Ðang khóa','Dang khoa'),
  @('Tên dang nh?p m?i','Ten dang nhap moi'),
  @('M?t kh?u t?m','Mat khau tam'),
  @('T?o tài kho?n','Tao tai khoan'),
  @('Ðang t?o...','Dang tao...'),
  @('Ðang t?i danh sách tài kho?n...','Dang tai danh sach tai khoan...'),
  @('Chua có tài kho?n d? hi?n th?.','Chua co tai khoan de hien thi.'),
  @('Tài kho?n','Tai khoan'),
  @('Vai trò h? th?ng','Vai tro he thong'),
  @('Vai trò hi?n th?','Vai tro hien thi'),
  @('Tr?ng thái','Trang thai'),
  @('Ðang ho?t d?ng','Dang hoat dong'),
  @('M? tài kho?n','Mo tai khoan'),
  @('Khóa tài kho?n','Khoa tai khoan'),
  @('Tài kho?n Admin không có quy?n qu?n lý tài kho?n ngu?i dùng. Ch? Owner du?c thao tác m?c này.','Tai khoan Admin khong co quyen quan ly tai khoan nguoi dung. Chi Owner duoc thao tac muc nay.'),
  @('Ðang xóa...','Dang xoa...')
)

foreach ($pair in $replacements) {
  $text = $text.Replace($pair[0], $pair[1])
}

[System.IO.File]::WriteAllText((Resolve-Path $path), $text, [System.Text.UTF8Encoding]::new($false))
